[package]
name = "ferriscraft-gl-experiments"
version = "0.1.0"
edition = "2024"

[dependencies]
egui_glium = "0.31.1"
glam = "0.30.5"
glium = "0.36.0"
image = "0.25.6"
rand = "0.9.2"
rayon = "1.11.0"
